name: RocketHire Prod Image Build

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: us-west-2
  COMPOSE_PROFILES: prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Create the env file on-build
        run: ./.env.prod.sh
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Builds the prod image
        run: docker-compose build
      - name: Docker login to AWS ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 687253468904.dkr.ecr.us-west-2.amazonaws.com
      - name: Docker push
        run: docker-compose push
